# Name of the application
spring.application.name=DailyDine

# Data source configuration for development profile
spring.datasource.url=jdbc:mysql://localhost:3306/dailydine
spring.datasource.username=root
spring.datasource.password=9016204659
#egrn ejrw xwly umbo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=9016204659
