# This Application have 2 Profiles
#   1. Development(dev)
#   2. Production(prod)
# As per the requirement we can access each profiles by changing the below value from dev to prod or prod to dev
spring.profiles.active=dev